server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 文件上传限制
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 5MB

# mybatisPlus配置
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

redis:
  host: 127.0.0.1
  port: 6379

oss:
  accessKey: m2kHOVjh_I2UQ9zKMqKEh_RkRJvA5NCK7d_nGaad
  secretKey: g8SqXIMXACPk20yhWpA8KnVc7DtmL2gTg4F731hl
  bucket: sg-blog1234567